server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: microservicios-eureka
          uri: https://github.com/canarioca/microservicios
          search-paths: config-data
  application:
    name: config-server